info:
  app:
    name: Catalog service from repo 1
    description: Product Catalog Microservice

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
	  